### ISSUE TITLE
Using curly braces with list get() inside double quotes causes syntax highlighting issues in themes.

### ISSUE THREAD

**Issue by x0rsw1tch** [luqimin/tinyvm#1]
When using curly braces surrounding a a list object reference with get() in velocity language mode causes this issue. There is another Velocity extension (sodatea/vscode-velocity) that doesn't exhibit this problem. Not too familiar with textmate so not sure how to fix this.

![image](https://user-images.githubusercontent.com/9543257/31834376-c5623dce-b59b-11e7-93fd-43468f31b512.png)

Here is what it looks like with sodatea/vscode-velocity:

![image](https://user-images.githubusercontent.com/9543257/31834308-7e4bdeea-b59b-11e7-99f1-69db0fe401a0.png)

Cheers and great extension!

**Comment by luqimin** [comment]
Thank you for your attention, you may try updating this plugin now

**Comment by x0rsw1tch** [comment]
Thank you, that did it!
